# Generated by Django 6.1.1 on 2026-09-07 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervalo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField()),
                ('profundidad_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profundidad_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diametro', models.DecimalField(decimal_places=3, help_text='Diámetro de hoyo o revestidor, en pulgadas.', max_digits=6)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['pozo', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Pozo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('operador', models.CharField(max_length=120)),
                ('ubicacion', models.CharField(max_length=120)),
                ('campo_area', models.CharField(blank=True, max_length=120)),
                ('fecha_spud', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('cantidad_unitaria', models.DecimalField(decimal_places=2, help_text='Cantidad por unidad de empaque (ej. 100, 50, 25, 5). Primer dato del antiguo Unit Size.', max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('LB', 'Libras (LB)'), ('KG', 'Kilogramos (KG)'), ('GA', 'Galones (GA)'), ('EA', 'Unidad (EA) — sin conversión de peso')], help_text='Unidad de esa cantidad (LB, KG, GA...). Segundo dato del antiguo Unit Size.', max_length=2)),
                ('tipo_empaque', models.CharField(choices=[('BG', 'Saco / Bolsa (BG)'), ('CN', 'Lata / Cuñete (CN)'), ('DM', 'Tambor (DM)'), ('TOTE', 'Tote'), ('BLS', 'Barril (BLS)'), ('EA', 'Unidad (EA) — sin empaque físico, ej. servicios')], help_text='Empaque en que viene esa cantidad (BG, CN, DM...). Tercer dato del antiguo Unit Size.', max_length=4)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad de empaque (por saco/tambor/lata/etc.), no por libra. Puede cambiar entre reportes.', max_digits=10)),
                ('gravedad_especifica', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PropiedadCatalogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.SlugField(help_text='Ej. "mud_weight", "pv", "r600".', unique=True)),
                ('nombre', models.CharField(help_text='Ej. "Peso del Lodo", "Viscosidad Plástica (PV)".', max_length=120)),
                ('unidad', models.CharField(blank=True, help_text='Ej. "lb/gal", "cP", "lb/100ft²". Vacío para adimensionales (ej. lecturas R600/R300).', max_length=30)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el reporte.')),
            ],
            options={
                'verbose_name': 'Propiedad (catálogo)',
                'verbose_name_plural': 'Propiedades (catálogo)',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SistemaFluido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre específico del sistema, ej. "Lodo Polimérico KCl".', max_length=120, unique=True)),
                ('categoria', models.CharField(choices=[('agua', 'Base Agua'), ('polimerico', 'Polimérico'), ('aceite', 'Base Aceite'), ('sintetico', 'Sintético (SBM)'), ('otro', 'Otro')], help_text='Categoría base: determina qué propiedades del catálogo maestro aplican.', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CierreVolumetrico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('volumen_final', models.DecimalField(decimal_places=2, help_text='Volumen final, en bbl.', max_digits=10)),
                ('volumen_no_fluido', models.DecimalField(decimal_places=2, help_text='Volumen que queda atrapado bajo la profundidad de cierre (Volume Not Fluids), en bbl.', max_digits=10)),
                ('perdida_left_in_hole', models.DecimalField(decimal_places=2, help_text='Pérdida registrada para que el balance del intervalo cuadre en cero, en bbl.', max_digits=10)),
                ('usuario', models.CharField(max_length=120)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('intervalo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cierre', to='reportes.intervalo')),
            ],
            options={
                'ordering': ['-fecha_cierre'],
            },
        ),
        migrations.AddField(
            model_name='intervalo',
            name='pozo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervalos', to='reportes.pozo'),
        ),
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('numero_reporte', models.PositiveIntegerField(editable=False, help_text='Correlativo por pozo, asignado automáticamente.')),
                ('actividad', models.CharField(blank=True, max_length=150)),
                ('peso_lodo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('intervalo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='reportes.intervalo')),
            ],
            options={
                'ordering': ['intervalo__pozo', 'numero_reporte'],
            },
        ),
        migrations.CreateModel(
            name='MuestraFluido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identificador', models.CharField(help_text='Ej. "TK 2 20:00", "TK 1 12:00".', max_length=60)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='reportes.reportediario')),
            ],
            options={
                'verbose_name': 'Muestra de fluido',
                'verbose_name_plural': 'Muestras de fluido',
                'ordering': ['reporte', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_final', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportes.producto')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='reportes.reportediario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='intervalo',
            name='sistema_fluido',
            field=models.ForeignKey(help_text='Sistema de fluido asignado a este intervalo. Fijo mientras el intervalo está abierto.', on_delete=django.db.models.deletion.PROTECT, related_name='intervalos', to='reportes.sistemafluido'),
        ),
        migrations.CreateModel(
            name='TuberiaInstalada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('revestidor', 'Revestidor'), ('liner', 'Liner'), ('otro', 'Otro')], default='revestidor', max_length=20)),
                ('longitud', models.DecimalField(decimal_places=2, help_text='Longitud en pies.', max_digits=10)),
                ('diametro_externo', models.DecimalField(decimal_places=3, help_text='OD en pulgadas.', max_digits=6)),
                ('diametro_interno', models.DecimalField(decimal_places=3, help_text='ID en pulgadas.', max_digits=6)),
                ('intervalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuberias', to='reportes.intervalo')),
            ],
            options={
                'ordering': ['intervalo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UsoMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_usada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hora_registro', models.TimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportes.producto')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='reportes.reportediario')),
            ],
            options={
                'ordering': ['reporte', 'hora_registro'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropiedadSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria_sistema', models.CharField(choices=[('agua', 'Base Agua'), ('polimerico', 'Polimérico'), ('aceite', 'Base Aceite'), ('sintetico', 'Sintético (SBM)'), ('otro', 'Otro')], max_length=20)),
                ('obligatoria', models.BooleanField(default=True, help_text='Si debe estar cargada para poder cerrar el reporte del día (cierre a las 12:00 a.m., sección 4).')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='reportes.propiedadcatalogo')),
            ],
            options={
                'verbose_name': 'Propiedad × Sistema (matriz)',
                'verbose_name_plural': 'Propiedades × Sistema (matriz)',
                'ordering': ['categoria_sistema', 'propiedad__orden'],
                'constraints': [models.UniqueConstraint(fields=('propiedad', 'categoria_sistema'), name='unica_propiedad_por_categoria_sistema')],
            },
        ),
        migrations.CreateModel(
            name='PropiedadValor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='reportes.muestrafluido')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='reportes.propiedadcatalogo')),
            ],
            options={
                'verbose_name': 'Valor de propiedad',
                'verbose_name_plural': 'Valores de propiedad',
                'ordering': ['muestra', 'propiedad__orden'],
                'constraints': [models.UniqueConstraint(fields=('muestra', 'propiedad'), name='unico_valor_por_muestra_y_propiedad')],
            },
        ),
        migrations.AddConstraint(
            model_name='reportediario',
            constraint=models.UniqueConstraint(fields=('intervalo', 'fecha'), name='unico_reporte_por_intervalo_y_fecha'),
        ),
        migrations.AddConstraint(
            model_name='inventarioitem',
            constraint=models.UniqueConstraint(fields=('reporte', 'producto'), name='unico_inventario_por_reporte_y_producto'),
        ),
        migrations.AddConstraint(
            model_name='intervalo',
            constraint=models.UniqueConstraint(fields=('pozo', 'numero'), name='unico_numero_intervalo_por_pozo'),
        ),
    ]
