# Generated by Django 6.1.1 on 2026-09-11 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_equipo_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervalo',
            name='es_sidetrack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intervalo',
            name='modo_operativo',
            field=models.CharField(choices=[('drilling', 'Drilling'), ('completion', 'Completion')], default='drilling', max_length=20),
        ),
        migrations.AddField(
            model_name='intervalo',
            name='profundidad_tope_liner_sidetrack',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='intervalo',
            name='tipo',
            field=models.CharField(choices=[('open_hole', 'Open Hole'), ('casing', 'Casing'), ('liner', 'Liner')], default='open_hole', max_length=20),
        ),
        migrations.AddField(
            model_name='intervalo',
            name='volumen_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pozo',
            name='air_gap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pozo',
            name='contratista',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pozo',
            name='es_offshore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pozo',
            name='nombre_taladro',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pozo',
            name='numero_logit',
            field=models.CharField(blank=True, help_text='Log-It Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pozo',
            name='sea_floor_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pozo',
            name='surface_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pozo',
            name='temp_gradient',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pozo',
            name='unit_set',
            field=models.CharField(choices=[('oilfield', 'Oilfield'), ('metric', 'Metric')], default='oilfield', max_length=20),
        ),
        migrations.AddField(
            model_name='pozo',
            name='usa_riser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pozo',
            name='water_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='CategoriaPerdida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modo_operativo', models.CharField(choices=[('drilling', 'Drilling'), ('completion', 'Completion')], max_length=20)),
                ('dominio', models.CharField(choices=[('superficial', 'Superficial'), ('subsuperficial', 'Subsuperficial')], max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_perdida', to='reportes.pozo')),
            ],
            options={
                'ordering': ['modo_operativo', 'dominio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Fosa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=120)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('active', 'Active'), ('reserve', 'Reserve'), ('premix', 'Premix'), ('spacer', 'Spacer'), ('storage', 'Storage'), ('dead_volume', 'Dead Volume')], default='active', max_length=30)),
                ('es_transaccional', models.BooleanField(default=True)),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fosas', to='reportes.pozo')),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='LecturaFosa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('volumen_medido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='reportes.fosa')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_fosa', to='reportes.reportediario')),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionFosa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('volumen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_transaccion', models.CharField(max_length=50)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('fosa_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_destino', to='reportes.fosa')),
                ('fosa_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_origen', to='reportes.fosa')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_fosa', to='reportes.reportediario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fosa',
            constraint=models.UniqueConstraint(fields=('pozo', 'descripcion'), name='unica_fosa_por_pozo'),
        ),
        migrations.AddConstraint(
            model_name='lecturafosa',
            constraint=models.UniqueConstraint(fields=('reporte', 'fosa'), name='unica_lectura_por_fosa_y_reporte'),
        ),
    ]
