# Generated by Django 6.1.1 on 2026-09-11 19:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_intervalo_es_sidetrack_intervalo_modo_operativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportediario',
            name='bit_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='bit_size',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='porcentaje_washout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='volumen_debajo_mecha',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='volumen_no_fluido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DistribucionTiempo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=150)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribucion_tiempo', to='reportes.reportediario')),
            ],
        ),
        migrations.CreateModel(
            name='TramoSarta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('drill_pipe', 'Drill Pipe'), ('heavy_weight', 'Heavy Weight'), ('drill_collar', 'Drill Collar'), ('sub', 'Sub')], max_length=30)),
                ('od', models.DecimalField(decimal_places=3, max_digits=6)),
                ('id_interno', models.DecimalField(decimal_places=3, max_digits=6)),
                ('longitud', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_sarta', to='reportes.reportediario')),
            ],
        ),
    ]
