# Generated by Django 6.1.1 on 2026-09-11 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_reportediario_bit_depth_reportediario_bit_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloMalla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fabricante', models.CharField(max_length=100)),
                ('api_mesh', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='usomaterial',
            name='on_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usomaterial',
            name='used_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='OperacionFiltracion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('suction_ntu', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discharge_ntu', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('porcentaje_solidos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cartridges_used', models.PositiveIntegerField(default=0)),
                ('de_sacks_used', models.PositiveIntegerField(default=0)),
                ('downtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('downtime_reason', models.CharField(blank=True, max_length=150)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtraciones', to='reportes.reportediario')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ldap_id', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linea_servicio', models.CharField(blank=True, max_length=100)),
                ('codigo_cobro', models.CharField(blank=True, max_length=50)),
                ('tarifa_diaria', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='reportes.pozo')),
            ],
        ),
        migrations.CreateModel(
            name='TicketTransferencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('numero_ticket', models.CharField(max_length=50)),
                ('tipo_ruta', models.CharField(choices=[('receive_warehouse', 'Receive from Warehouse'), ('receive_well', 'Receive from Other Well'), ('return_warehouse', 'Return to Warehouse'), ('return_well', 'Return to Other Well')], max_length=30)),
                ('origen_destino', models.CharField(blank=True, max_length=150)),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='reportes.pozo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportes.producto')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='reportes.tickettransferencia')),
            ],
        ),
        migrations.CreateModel(
            name='UsoMalla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('installed', 'Installed'), ('reused', 'Reused'), ('disposed', 'Disposed'), ('undo', 'Undo')], default='installed', max_length=20)),
                ('horas_uso', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportes.equipo')),
                ('malla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportes.modelomalla')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mallas', to='reportes.reportediario')),
            ],
        ),
    ]
