# Generated by Django 6.1.1 on 2026-09-12 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_modelomalla_usomaterial_on_order_and_more'),
        ('reportes', '0008_interval_closeout'),
    ]

    operations = [
    ]
