# Generated by Django 6.1.1 on 2026-09-12 01:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0009_merge_20260911_2104'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='pit',
                    name='unica_descripcion_fosa_por_pozo',
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='cierrevolumetrico',
            name='fosa_origen',
            field=models.ForeignKey(blank=True, help_text='Fosa de la que se descuenta el volumen atrapado. Obligatoria si volumen_no_fluido > 0.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_left_in_hole', to='reportes.fosa'),
        ),
        migrations.AlterModelOptions(
            name='categoriaperdida',
            options={'ordering': ['pozo', 'modo_operativo', 'dominio', 'nombre'], 'verbose_name': 'Categoría de pérdida', 'verbose_name_plural': 'Categorías de pérdida (Loss Setup)'},
        ),
        migrations.AlterModelOptions(
            name='detalleticket',
            options={'verbose_name': 'Detalle de Ticket', 'verbose_name_plural': 'Detalles de Tickets'},
        ),
        migrations.AlterModelOptions(
            name='distribuciontiempo',
            options={'ordering': ['reporte', 'orden'], 'verbose_name': 'Distribución de tiempo', 'verbose_name_plural': 'Distribución de tiempo (Time Distribution)'},
        ),
        migrations.AlterModelOptions(
            name='fosa',
            options={'ordering': ['pozo', 'descripcion'], 'verbose_name': 'Fosa / Tanque', 'verbose_name_plural': 'Fosas / Tanques'},
        ),
        migrations.AlterModelOptions(
            name='lecturafosa',
            options={'ordering': ['reporte', 'fosa'], 'verbose_name': 'Lectura de fosa', 'verbose_name_plural': 'Lecturas de fosa (Volumen Medido)'},
        ),
        migrations.AlterModelOptions(
            name='modelomalla',
            options={'verbose_name': 'Modelo de Malla', 'verbose_name_plural': 'Modelos de Malla (Screens Setup)'},
        ),
        migrations.AlterModelOptions(
            name='operacionfiltracion',
            options={'verbose_name': 'Operación de Filtración', 'verbose_name_plural': 'Operaciones de Filtración (Filtration Tab)'},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'Personal', 'verbose_name_plural': 'Personal (Personnel Setup)'},
        ),
        migrations.AlterModelOptions(
            name='tickettransferencia',
            options={'verbose_name': 'Ticket de Transferencia', 'verbose_name_plural': 'Tickets de Transferencia'},
        ),
        migrations.AlterModelOptions(
            name='tramosarta',
            options={'ordering': ['reporte', 'orden'], 'verbose_name': 'Tramo de sarta', 'verbose_name_plural': 'Tramos de sarta (Drill String Geometry)'},
        ),
        migrations.AlterModelOptions(
            name='transaccionfosa',
            options={'ordering': ['reporte', 'hora_registro'], 'verbose_name': 'Transacción de fosa', 'verbose_name_plural': 'Transacciones de fosa (Volume Accounting)'},
        ),
        migrations.AlterModelOptions(
            name='usomalla',
            options={'verbose_name': 'Uso de Malla', 'verbose_name_plural': 'Uso de Mallas (Daily Screens)'},
        ),
        migrations.RemoveConstraint(
            model_name='fosa',
            name='unica_fosa_por_pozo',
        ),
        migrations.RemoveConstraint(
            model_name='lecturafosa',
            name='unica_lectura_por_fosa_y_reporte',
        ),
        migrations.RemoveField(
            model_name='tramosarta',
            name='id_interno',
        ),
        migrations.RemoveField(
            model_name='tramosarta',
            name='od',
        ),
        migrations.RemoveField(
            model_name='transaccionfosa',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='transaccionfosa',
            name='tipo_transaccion',
        ),
        migrations.AddField(
            model_name='categoriaperdida',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='distribuciontiempo',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='distribuciontiempo',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='circulating_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Horas circulando lodo en las últimas 24 hrs.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='midnight_depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Midnight Depth: profundidad al inicio de la jornada (00:00 hrs), en ft.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='rotating_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Horas rotando / perforando en las últimas 24 hrs.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='total_depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Depth (MD): profundidad total medida del pozo, en ft.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='tvd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='True Vertical Depth: profundidad vertical verdadera, en ft.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tramosarta',
            name='diametro_externo',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Pipe OD, en pulgadas.', max_digits=6),
        ),
        migrations.AddField(
            model_name='tramosarta',
            name='diametro_interno',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Pipe ID, en pulgadas.', max_digits=6),
        ),
        migrations.AddField(
            model_name='tramosarta',
            name='es_principal',
            field=models.BooleanField(default=False, help_text='Tramo con longitud autocalculada (Bit Depth − resto de la sarta). Como máximo uno por reporte.'),
        ),
        migrations.AddField(
            model_name='tramosarta',
            name='longitud_tool_joint',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='TJ Length, en pulgadas.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tramosarta',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de la tabla, de arriba (superficie) hacia abajo.'),
        ),
        migrations.AddField(
            model_name='tramosarta',
            name='tool_joint_id',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Tool Jt ID, en pulgadas.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tramosarta',
            name='tool_joint_od',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Tool Jt OD, en pulgadas.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='transaccionfosa',
            name='cantidad_usada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad de empaques usados (sacos/tambores/etc.). Solo para Add Chemicals.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaccionfosa',
            name='categoria_perdida',
            field=models.ForeignKey(blank=True, help_text='Obligatoria para Loss; debe pertenecer al mismo pozo y modo operativo del intervalo.', null=True, on_delete=django.db.models.deletion.PROTECT, to='reportes.categoriaperdida'),
        ),
        migrations.AddField(
            model_name='transaccionfosa',
            name='es_dilucion',
            field=models.BooleanField(default=False, help_text='Is Dilution: el producto agregado es agua/base líquida usada para diluir la fosa destino.'),
        ),
        migrations.AddField(
            model_name='transaccionfosa',
            name='hora_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaccionfosa',
            name='intervalo',
            field=models.ForeignKey(blank=True, editable=False, help_text='Snapshot inmutable de reporte.intervalo al momento de crear la transacción (manual 6.3).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_fosa', to='reportes.intervalo'),
        ),
        migrations.AddField(
            model_name='transaccionfosa',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaccionfosa',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Solo para Add Chemicals.', null=True, on_delete=django.db.models.deletion.PROTECT, to='reportes.producto'),
        ),
        migrations.AddField(
            model_name='transaccionfosa',
            name='tipo',
            field=models.CharField(choices=[('add_chemicals', 'Add Chemicals'), ('loss', 'Loss'), ('transfer', 'Transfer')], default='add_chemicals', max_length=20),
        ),
        migrations.AlterField(
            model_name='categoriaperdida',
            name='dominio',
            field=models.CharField(choices=[('superficial', 'Superficial'), ('subsuperficial', 'Subsuperficial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='categoriaperdida',
            name='modo_operativo',
            field=models.CharField(choices=[('drilling', 'Drilling'), ('completion', 'Completion')], max_length=12),
        ),
        migrations.AlterField(
            model_name='categoriaperdida',
            name='nombre',
            field=models.CharField(help_text='Ej. "Shakers", "Evaporation", "Left in Hole".', max_length=80),
        ),
        migrations.AlterField(
            model_name='categoriaperdida',
            name='pozo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_perdida', to='reportes.pozo'),
        ),
        migrations.AlterField(
            model_name='cierrevolumetrico',
            name='volumen_final',
            field=models.DecimalField(decimal_places=2, help_text='Final Volume, en bbl.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='distribuciontiempo',
            name='actividad',
            field=models.CharField(help_text='Ej. "Rotary Drilling", "Circulating", "Tripping In".', max_length=100),
        ),
        migrations.AlterField(
            model_name='distribuciontiempo',
            name='horas',
            field=models.DecimalField(decimal_places=2, help_text='Horas dedicadas a esta actividad (mayor a 0, hasta 24).', max_digits=4),
        ),
        migrations.AlterField(
            model_name='fosa',
            name='capacidad',
            field=models.DecimalField(decimal_places=2, help_text='Capacidad volumétrica máxima, en bbl.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fosa',
            name='descripcion',
            field=models.CharField(help_text='Nombre único de la fosa, ej. "Active 1", "Reserve 1", "Premix 1".', max_length=80),
        ),
        migrations.AlterField(
            model_name='fosa',
            name='es_transaccional',
            field=models.BooleanField(default=True, help_text='Si es False, es una fosa/tanque no transaccional (almacenamiento aislado, ej. Base Oil Storage): no participa del balance diario de lodo activo.'),
        ),
        migrations.AlterField(
            model_name='fosa',
            name='pozo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fosas', to='reportes.pozo'),
        ),
        migrations.AlterField(
            model_name='fosa',
            name='tipo',
            field=models.CharField(choices=[('active', 'Active'), ('reserve', 'Reserve'), ('premix', 'Premix'), ('spacer', 'Spacer'), ('storage', 'Storage'), ('dead_volume', 'Dead Volume')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervalo',
            name='es_sidetrack',
            field=models.BooleanField(default=False, help_text='Si este intervalo se abre por un desvío (side track) del hoyo.'),
        ),
        migrations.AlterField(
            model_name='intervalo',
            name='modo_operativo',
            field=models.CharField(choices=[('drilling', 'Drilling'), ('completion', 'Completion')], default='drilling', help_text='Operational Mode: Drilling o Completion.', max_length=12),
        ),
        migrations.AlterField(
            model_name='intervalo',
            name='profundidad_tope_liner_sidetrack',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Top Of Liner / Sidetrack (ft). Obligatorio si tipo=Liner o es_sidetrack=True.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='intervalo',
            name='tipo',
            field=models.CharField(choices=[('casing', 'Casing'), ('liner', 'Liner'), ('open_hole', 'Open Hole')], default='open_hole', help_text='Type: Casing, Liner u Open Hole.', max_length=10),
        ),
        migrations.AlterField(
            model_name='intervalo',
            name='volumen_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Start Volume (bbl). Se puebla automáticamente al crear el intervalo con el Final Volume del cierre del intervalo anterior del mismo pozo (Rollover, manual 7.2). Para el primer intervalo del pozo se ingresa a mano.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lecturafosa',
            name='fosa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas', to='reportes.fosa'),
        ),
        migrations.AlterField(
            model_name='lecturafosa',
            name='volumen_medido',
            field=models.DecimalField(decimal_places=4, help_text='Lectura física de la fosa, en bbl.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='air_gap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Air Gap, en ft.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='campo_area',
            field=models.CharField(blank=True, help_text='Field Name/Block.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='contratista',
            field=models.CharField(blank=True, help_text='Contractor.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='es_offshore',
            field=models.BooleanField(default=False, help_text='Se bloquea permanentemente al crear el primer reporte diario.', verbose_name='¿Es offshore?'),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='nombre_taladro',
            field=models.CharField(blank=True, help_text='Rig Name.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='numero_logit',
            field=models.CharField(blank=True, help_text='Log-It Number: identificador único de seguimiento corporativo.', max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='sea_floor_temp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sea Floor Temp, en °F.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='surface_temp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Surface Temp, en °F.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='temp_gradient',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temp Gradient, en °F/100ft.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='unit_set',
            field=models.CharField(choices=[('oilfield', 'Standard Oilfield (ft, in, bbl, lb/gal)'), ('metric', 'Metric')], default='oilfield', help_text='Se bloquea permanentemente al crear el primer reporte diario.', max_length=10),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='usa_riser',
            field=models.BooleanField(default=False, help_text='Se bloquea permanentemente al crear el primer reporte diario.', verbose_name='Usa riser'),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='water_depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Water Depth, en ft.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='reportediario',
            name='bit_depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bit Depth: profundidad actual de la mecha, en ft.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reportediario',
            name='bit_size',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Bit Size: diámetro nominal de la mecha, en pulgadas.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='reportediario',
            name='porcentaje_washout',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='% Washout (ensanchamiento del hoyo). 0 = hoyo en calibre (gauge hole).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reportediario',
            name='volumen_debajo_mecha',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Vol. Debajo de la Mecha (bbl): hoyo abierto por debajo de la broca, no cubierto por la sarta.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='reportediario',
            name='volumen_no_fluido',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Volume Not Fluids (bbl): volumen dentro del hoyo que no pertenece al fluido circulante activo (ej. agua salada de perforación inicial, lodo previo en proceso de desplazamiento). Se resta del Total Hole Volume para obtener el Fluid Volume.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tramosarta',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longitud (ft). Si es_principal=True se recalcula siempre al guardar; el valor enviado se ignora.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tramosarta',
            name='tipo',
            field=models.CharField(choices=[('drill_pipe', 'Drill Pipe'), ('heavy_weight', 'Heavy Weight'), ('drill_collar', 'Drill Collar'), ('sub', 'Sub')], default='drill_pipe', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccionfosa',
            name='fosa_destino',
            field=models.ForeignKey(blank=True, help_text='Fosa a la que entra el volumen (Add Chemicals, Transfer).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_entrada', to='reportes.fosa'),
        ),
        migrations.AlterField(
            model_name='transaccionfosa',
            name='fosa_origen',
            field=models.ForeignKey(blank=True, help_text='Fosa de la que sale el volumen (Loss, Transfer).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_salida', to='reportes.fosa'),
        ),
        migrations.AlterField(
            model_name='transaccionfosa',
            name='volumen',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Volumen desplazado, en bbl. Para Add Chemicals se recalcula siempre al guardar (el valor enviado se ignora); para Loss y Transfer es un dato medido/manual.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='tuberiainstalada',
            name='diametro_externo',
            field=models.DecimalField(decimal_places=3, help_text='Casing OD, en pulgadas.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='tuberiainstalada',
            name='diametro_interno',
            field=models.DecimalField(decimal_places=3, help_text='Casing ID, en pulgadas.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='tuberiainstalada',
            name='longitud',
            field=models.DecimalField(decimal_places=2, help_text='Longitud/Depth (MD) en pies.', max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='categoriaperdida',
            constraint=models.UniqueConstraint(fields=('pozo', 'modo_operativo', 'nombre'), name='unica_categoria_perdida_por_pozo_y_modo'),
        ),
        migrations.AddConstraint(
            model_name='fosa',
            constraint=models.UniqueConstraint(fields=('pozo', 'descripcion'), name='unica_descripcion_fosa_por_pozo'),
        ),
        migrations.AddConstraint(
            model_name='lecturafosa',
            constraint=models.UniqueConstraint(fields=('reporte', 'fosa'), name='unica_lectura_por_reporte_y_fosa'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Pit',
                ),
            ],
            database_operations=[],
        ),
    ]
