# Generated by Django 6.1.1 on 2026-09-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único identificador del producto (SKU)', max_length=50, unique=True, verbose_name='Código del Producto')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('unidad', models.CharField(help_text='Ej: SACOS 55 LBS, TAMBOR 55 GLS, TOTE', max_length=50, verbose_name='Unidad / Presentación')),
                ('libraje', models.DecimalField(decimal_places=2, default=0.0, help_text='Peso o libraje unitario en libras', max_digits=12, verbose_name='Libraje (LBS)')),
                ('gravedad', models.DecimalField(decimal_places=4, default=1.0, max_digits=8, verbose_name='Gravedad Específica')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Costo Unitario ($)')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Cantidad (Stock)')),
                ('categoria', models.CharField(choices=[('SOLIDO', 'Sólido'), ('LIQUIDO', 'Líquido')], default='SOLIDO', max_length=10, verbose_name='Categoría')),
                ('estado', models.CharField(choices=[('ALTO', 'Stock Alto'), ('MEDIO', 'Stock Medio'), ('BAJO', 'Stock Bajo')], default='ALTO', max_length=10, verbose_name='Estado de Stock')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto de Inventario',
                'verbose_name_plural': 'Productos de Inventario',
                'ordering': ['codigo'],
            },
        ),
    ]
