# Generated by Django 6.1.1 on 2026-09-16 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Pozo')),
                ('sistema_unidades', models.CharField(choices=[('STANDARD_OILFIELD', 'Standard Oilfield'), ('STANDARD_1', 'Standard 1 (lb/ft³)'), ('STANDARD_2', 'Standard 2 (m)'), ('STANDARD_3', 'Standard 3 (m, m/min)'), ('SI_METRIC', 'SI Métrico'), ('METRIC_1', 'Métrico 1'), ('METRIC_2', 'Métrico 2'), ('METRIC_3', 'Métrico 3'), ('METRIC_4', 'Métrico 4'), ('METRIC_5', 'Métrico 5'), ('CUSTOM', 'Personalizado')], default='STANDARD_OILFIELD', max_length=20, verbose_name='Sistema de Unidades')),
                ('unidades_bloqueadas', models.BooleanField(default=False, help_text='Se activa automáticamente al confirmar el paso 4 del wizard.', verbose_name='Unidades Bloqueadas')),
                ('moneda_simbolo', models.CharField(default='USD', max_length=6, verbose_name='Símbolo de Moneda')),
                ('moneda_decimales', models.PositiveSmallIntegerField(default=2, verbose_name='Decimales de Moneda')),
                ('tasa_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasa de Impuesto (%)')),
                ('ecuacion_solidos_base_agua', models.CharField(choices=[('MI', 'M-I'), ('API', 'API')], default='MI', max_length=5, verbose_name='Ecuación de Sólidos — Base Agua')),
                ('ecuacion_solidos_base_aceite', models.CharField(choices=[('MI', 'M-I'), ('API', 'API')], default='MI', max_length=5, verbose_name='Ecuación de Sólidos — Base Aceite/Sintética')),
                ('categoria_perdida_tipo', models.CharField(choices=[('MI', 'M-I'), ('UK', 'UK'), ('HYDRO', 'Hydro'), ('STATOIL', 'Statoil'), ('IFE', 'IFE'), ('COMPLETION_FLUIDS', 'Completion Fluids'), ('CUSTOM', 'Personalizado')], default='MI', max_length=20, verbose_name='Categorías de Pérdida')),
                ('fecha_primera_captura', models.DateField(blank=True, help_text='Inmutable una vez confirmada. Puede ser anterior a la fecha de spud.', null=True, verbose_name='Primera Fecha de Datos')),
                ('tipo_fluido_inicial', models.CharField(blank=True, choices=[('WATER_BASE', 'Base Agua'), ('WATER_BASE_CACL2', 'Base Agua (CaCl2)'), ('OIL_BASE', 'Base Aceite'), ('SYNTHETIC_BASE', 'Base Sintética'), ('COMPLETION_FLUIDS', 'Fluidos de Completación')], max_length=20, null=True, verbose_name='Tipo de Fluido — Primer Chequeo')),
                ('con_tratamiento_disposicion', models.BooleanField(default=False, verbose_name='Con Tratamiento y Disposición de Desechos')),
                ('numero_control_logit', models.CharField(blank=True, max_length=50, verbose_name='Número de Control de Proyecto Log-It')),
                ('spud_date_completado', models.BooleanField(default=False, verbose_name='Pantalla Spud Date completada')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (en creación)'), ('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('paso_wizard_actual', models.PositiveSmallIntegerField(default=1, verbose_name='Último paso guardado del wizard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('pozo_plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pozos_clonados', to='operaciones.pozo', verbose_name='Pozo usado como plantilla')),
            ],
            options={
                'verbose_name': 'Pozo',
                'verbose_name_plural': 'Pozos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaPerdidaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveSmallIntegerField(verbose_name='Código')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('SUPERFICIE', 'Superficie'), ('SUBSUELO', 'Subsuelo')], default='SUPERFICIE', max_length=12, verbose_name='Superficie / Subsuelo')),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_perdida', to='operaciones.pozo')),
            ],
            options={
                'verbose_name': 'Categoría de Pérdida',
                'verbose_name_plural': 'Categorías de Pérdida',
                'ordering': ['codigo'],
                'unique_together': {('pozo', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='PropiedadUnidadPozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propiedad', models.CharField(choices=[('PROFUNDIDAD', 'Profundidad (Depth)'), ('HOYO_TUBERIA', 'Hoyo/Tubería (Hole/Pipe Size)'), ('VOLUMEN', 'Volumen'), ('CAUDAL', 'Caudal (Flow Rate)'), ('BOQUILLA_BROCA', 'Tamaño de Boquilla (Bit-Nozzle Size)'), ('VELOCIDAD', 'Velocidad'), ('PRESION', 'Presión'), ('FACTOR_K', 'Factor K'), ('PESO_FLUIDO', 'Peso de Fluido'), ('VISCOSIDAD_PLASTICA', 'Viscosidad Plástica'), ('PUNTO_CEDENCIA_GELES', 'Punto de Cedencia y Geles'), ('VELOCIDAD_CHORRO', 'Velocidad de Chorro (Jet Velocity)'), ('CONCENTRACION_PRODUCTO', 'Concentración de Producto'), ('FUERZA', 'Fuerza'), ('TEMPERATURA', 'Temperatura'), ('ESPESOR_TORTA', 'Espesor de Revoque (Filter-Cake Thickness)')], max_length=30)),
                ('unidad', models.CharField(max_length=20, verbose_name='Unidad Elegida')),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_personalizadas', to='operaciones.pozo')),
            ],
            options={
                'verbose_name': 'Unidad Personalizada del Pozo',
                'verbose_name_plural': 'Unidades Personalizadas del Pozo',
                'ordering': ['propiedad'],
                'unique_together': {('pozo', 'propiedad')},
            },
        ),
    ]
