# Generated by Django 6.1.1 on 2026-09-16 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_wellheaderinfo_fosa_intervalorevestimiento_tipofosa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fosa',
            options={'ordering': ['numero'], 'verbose_name': 'Fosa / Tanque', 'verbose_name_plural': 'Fosas y Tanques'},
        ),
        migrations.AlterModelOptions(
            name='tipofosa',
            options={'ordering': ['codigo'], 'verbose_name': 'Tipo de Fosa', 'verbose_name_plural': 'Tipos de Fosa'},
        ),
        migrations.AlterModelOptions(
            name='wellheaderinfo',
            options={'verbose_name': 'Información General del Pozo', 'verbose_name_plural': 'Información General del Pozo'},
        ),
        migrations.AddField(
            model_name='pozo',
            name='usar_api_5ta_edicion_hidraulica',
            field=models.BooleanField(default=False, verbose_name='Usar API 5ta Edición para Cálculo Hidráulico'),
        ),
        migrations.AlterField(
            model_name='fosa',
            name='capacidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='fosa',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='fosa',
            name='numero',
            field=models.PositiveSmallIntegerField(verbose_name='N° de Fosa'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='casing_id_in',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='ID Revestimiento (in)'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='casing_od_in',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='OD Revestimiento (in)'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='comentarios_recap',
            field=models.TextField(blank=True, help_text='Hasta 10,000 caracteres.', verbose_name='Comentarios del Intervalo para Recap'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='fluid_type_code_1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código de Tipo de Fluido 1'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='fluid_type_code_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código de Tipo de Fluido 2'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='frac_grad_lb_gal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Gradiente de Fractura (lb/gal)'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='hole_size_in',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Diámetro de Hoyo (in)'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='interval_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Costo del Intervalo ($)'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='interval_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Días del Intervalo'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='max_bht_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temperatura Máx. de Fondo — BHT (°F)'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='maximum_angle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ángulo Máximo'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='maximum_density_lb_gal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Densidad Máxima (lb/gal)'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='numero_intervalo',
            field=models.PositiveSmallIntegerField(verbose_name='Número de Intervalo'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='observaciones_recomendaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones y Recomendaciones'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='planned_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Costo Planeado ($)'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='planned_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Días Planeados'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='planned_length_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Longitud Planeada (ft)'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='profundidad_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profundidad (ft)'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CONDUCTOR', 'Conductor'), ('SUPERFICIE', 'Superficie'), ('INTERMEDIO', 'Intermedio'), ('PRODUCCION', 'Producción'), ('LINER', 'Liner'), ('CASING', 'Revestimiento'), ('HOYO_ABIERTO', 'Hoyo Abierto')], max_length=15, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='intervalorevestimiento',
            name='top_of_liner_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tope de Liner (ft)'),
        ),
        migrations.AlterField(
            model_name='tipofosa',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='air_gap_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altura Libre — Air Gap (ft)'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='almacen',
            field=models.CharField(blank=True, max_length=150, verbose_name='Almacén'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='comentarios',
            field=models.TextField(blank=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='completado',
            field=models.BooleanField(default=False, verbose_name='Información del Pozo guardada al menos una vez'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='completion_fluid_type_codigo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo de Fluido de Completación — Código'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='completion_fluid_type_descripcion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo de Fluido de Completación'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='contract_type_codigo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo de Contrato — Código'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='contract_type_descripcion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='contratista',
            field=models.CharField(blank=True, max_length=150, verbose_name='Contratista'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='field_area',
            field=models.CharField(blank=True, max_length=150, verbose_name='Campo/Área'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='horiz_displacement_ft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se usa para identificar pozos de Alcance Extendido (Extended Reach).', max_digits=10, null=True, verbose_name='Desplazamiento Horizontal (ft)'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='ingeniero_miswaco_1',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ingeniero M-I SWACO 1'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='ingeniero_miswaco_2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ingeniero M-I SWACO 2'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='ingeniero_proyecto',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ingeniero de Proyecto'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='latitud_ns_indicador',
            field=models.CharField(blank=True, max_length=20, verbose_name='Indicador de Latitud N/S'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='longitud_ew_indicador',
            field=models.CharField(blank=True, max_length=20, verbose_name='Indicador de Longitud E/O'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='marketing_codes_completado',
            field=models.BooleanField(default=False, verbose_name='Códigos de Mercadeo guardados al menos una vez'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='maximum_temperature_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temperatura Máxima (°F)'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='nombre_taladro',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre del Taladro'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='numero_control_logit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Control de Proyecto Log-It'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='operador',
            field=models.CharField(blank=True, max_length=150, verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='primary_mud_type_codigo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo de Lodo Principal — Código'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='primary_mud_type_descripcion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo de Lodo Principal'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='re_entry_depth_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profundidad de Reentrada (ft)'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='sea_floor_temp_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temperatura del Lecho Marino (°F)'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='spud_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Spud'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='surface_temp_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temperatura Superficial (°F)'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='td_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de TD'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='td_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Días de TD'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='temp_gradient_f_100ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Gradiente de Temperatura (°F/100ft)'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculado; se deja manual hasta integrar el módulo de costos.', max_digits=14, null=True, verbose_name='Costo Total ($)'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='total_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Días Totales'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='total_depth_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profundidad Total (ft)'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='water_depth_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profundidad de Agua (ft)'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='well_type_codigo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo de Pozo — Código'),
        ),
        migrations.AlterField(
            model_name='wellheaderinfo',
            name='well_type_descripcion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo de Pozo'),
        ),
        migrations.CreateModel(
            name='AlmacenCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Almacén')),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenes', to='operaciones.pozo')),
            ],
            options={
                'verbose_name': 'Código de Almacén',
                'verbose_name_plural': 'Códigos de Almacén',
                'ordering': ['codigo'],
                'unique_together': {('pozo', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='TipoDistribucionTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('descripcion', models.CharField(max_length=120, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('DF', 'DF'), ('CF', 'CF'), ('DF/CF', 'DF/CF')], default='DF', max_length=5, verbose_name='Tipo')),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_distribucion_tiempo', to='operaciones.pozo')),
            ],
            options={
                'verbose_name': 'Tipo de Distribución de Tiempo',
                'verbose_name_plural': 'Tipos de Distribución de Tiempo',
                'ordering': ['numero'],
                'unique_together': {('pozo', 'numero')},
            },
        ),
    ]
