# Generated by Django 6.1.1 on 2026-09-17 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_alter_fosa_options_alter_tipofosa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código de Equipo')),
                ('nombre', models.CharField(help_text="Nombre oficial del equipo (equivalente a 'Equip. Detail' de ONE-TRAX); no debería modificarse al usarlo en un pozo.", max_length=150, verbose_name='Nombre Oficial')),
            ],
            options={
                'verbose_name': 'Equipo (Catálogo Maestro)',
                'verbose_name_plural': 'Equipos (Catálogo Maestro)',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MallaZaranda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código de Malla')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('mesh_size', models.PositiveSmallIntegerField(verbose_name='Tamaño de Malla (Mesh)')),
            ],
            options={
                'verbose_name': 'Malla de Zaranda (Catálogo Maestro)',
                'verbose_name_plural': 'Mallas de Zaranda (Catálogo Maestro)',
                'ordering': ['mesh_size', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ProductoActivoPozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviatura', models.CharField(blank=True, max_length=30, verbose_name='Abreviación')),
                ('unit_size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tamaño de Unidad')),
                ('unidad', models.CharField(blank=True, max_length=30, verbose_name='Unidad')),
                ('empaque', models.CharField(blank=True, max_length=30, verbose_name='Empaque')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Precio')),
                ('gravedad_especifica', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Gravedad Específica')),
                ('calcular_concentracion', models.BooleanField(default=True, verbose_name='¿Calcular Concentración?')),
                ('es_producto_mi', models.BooleanField(default=True, verbose_name='¿Producto M-I?')),
                ('grupo_producto', models.PositiveSmallIntegerField(default=1, verbose_name='Grupo de Producto')),
                ('codigo_costo_diario', models.PositiveSmallIntegerField(default=1, verbose_name='Código de Costo Diario')),
                ('calcular_wmgt_conc', models.BooleanField(default=True, verbose_name='¿Calcular Conc. WMgt?')),
                ('categoria_costo_wmgt', models.PositiveSmallIntegerField(default=1, verbose_name='Categoría de Costo WMgt')),
                ('categoria_costo_cf', models.PositiveSmallIntegerField(default=1, verbose_name='Categoría de Costo CF')),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_activos', to='operaciones.pozo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_en_pozos', to='operaciones.producto', verbose_name='Producto (Catálogo Maestro)')),
            ],
            options={
                'verbose_name': 'Producto Activo del Pozo',
                'verbose_name_plural': 'Productos Activos del Pozo',
                'ordering': ['producto__codigo'],
            },
        ),
        migrations.CreateModel(
            name='EquipoActivoPozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=30, verbose_name='N° de Serie')),
                ('descripcion', models.CharField(blank=True, help_text='Editable para necesidades de reporte; el nombre oficial vive en el Equipo maestro.', max_length=150, verbose_name='Descripción')),
                ('precio_renta', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de Renta')),
                ('precio_standby', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio Stand-By')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_en_pozos', to='operaciones.equipo', verbose_name='Equipo (Catálogo Maestro)')),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_activos', to='operaciones.pozo')),
            ],
            options={
                'verbose_name': 'Equipo Activo del Pozo',
                'verbose_name_plural': 'Equipos Activos del Pozo',
                'ordering': ['equipo__codigo', 'numero_serie'],
                'unique_together': {('pozo', 'numero_serie')},
            },
        ),
        migrations.CreateModel(
            name='MallaActivaPozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mallas_activas', to='operaciones.pozo')),
                ('malla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activas_en_pozos', to='operaciones.mallazaranda', verbose_name='Malla (Catálogo Maestro)')),
            ],
            options={
                'verbose_name': 'Malla Activa del Pozo',
                'verbose_name_plural': 'Mallas Activas del Pozo',
                'ordering': ['malla__mesh_size'],
                'unique_together': {('pozo', 'malla')},
            },
        ),
    ]
