# Generated by Django 6.1.1 on 2026-09-17 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_equipo_mallazaranda_productoactivopozo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.CharField(choices=[('CENTRIFUGA', 'Centrífuga'), ('LIMPIADOR_LODO', 'Limpiador de Lodo (Mud Cleaner)'), ('ZARANDA', 'Zaranda (Shale Shaker)'), ('SISTEMA_VACIO', 'Sistema de Vacío'), ('CONTENEDOR_RECORTES', 'Contenedor de Recortes'), ('OTROS', 'Otros')], default='OTROS', help_text="Agrupa el equipo para 'Equipment Properties Setup' (Centrífuga, Mud Cleaner, Shale Shaker, etc.).", max_length=25, verbose_name='Tipo de Equipo'),
        ),
        migrations.CreateModel(
            name='CentrifugaUnidadConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_flow_rate', models.CharField(choices=[('gal/min', 'gal/min'), ('bbl/min', 'bbl/min'), ('bbl/hr', 'bbl/hr'), ('L/min', 'L/min'), ('m3/hr', 'm3/hr')], default='gal/min', max_length=15, verbose_name='Unidad de Flow Rate')),
                ('unidad_mass', models.CharField(choices=[('Ton', 'Ton'), ('lb', 'lb'), ('kg', 'kg'), ('bbl', 'bbl')], default='Ton', max_length=10, verbose_name='Unidad de Mass')),
                ('pozo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='centrifuga_unidad_config', to='operaciones.pozo')),
            ],
            options={
                'verbose_name': 'Configuración de Unidades de Centrífuga',
                'verbose_name_plural': 'Configuraciones de Unidades de Centrífuga',
            },
        ),
        migrations.CreateModel(
            name='EquipoPropiedadExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('CENTRIFUGA', 'Centrífuga'), ('LIMPIADOR_LODO', 'Limpiador de Lodo (Mud Cleaner)'), ('ZARANDA', 'Zaranda (Shale Shaker)'), ('SISTEMA_VACIO', 'Sistema de Vacío'), ('CONTENEDOR_RECORTES', 'Contenedor de Recortes'), ('OTROS', 'Otros')], max_length=25, verbose_name='Tipo de Equipo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('unidad', models.CharField(blank=True, max_length=30, verbose_name='Unidad')),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades_equipo_extra', to='operaciones.pozo')),
            ],
            options={
                'verbose_name': 'Propiedad de Equipo Extra',
                'verbose_name_plural': 'Propiedades de Equipo Extra',
                'ordering': ['tipo_equipo', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ParametroBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(help_text="Categoría para agrupar en la lista de selección (ej: 'Mud Properties').", max_length=60, verbose_name='Grupo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('unidad', models.CharField(blank=True, max_length=30, verbose_name='Unidad')),
                ('tipo_fluido', models.CharField(choices=[('WBM', 'WBM (Base Agua)'), ('OBM', 'OBM (Base Aceite)'), ('AMBOS', 'Ambos'), ('NA', 'No Aplica')], default='NA', max_length=5, verbose_name='Tipo de Fluido')),
                ('tipo_dato', models.CharField(choices=[('NUMERICO', 'Numérico (valor único)'), ('MIN_MAX', 'Mínimo / Máximo'), ('TEXTO', 'Texto')], default='MIN_MAX', max_length=10, verbose_name='Tipo de Dato')),
            ],
            options={
                'verbose_name': 'Parámetro de Benchmark (Catálogo Maestro)',
                'verbose_name_plural': 'Parámetros de Benchmark (Catálogo Maestro)',
                'ordering': ['grupo', 'descripcion'],
                'unique_together': {('grupo', 'descripcion', 'tipo_fluido')},
            },
        ),
        migrations.CreateModel(
            name='PropiedadEquipoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('CENTRIFUGA', 'Centrífuga'), ('LIMPIADOR_LODO', 'Limpiador de Lodo (Mud Cleaner)'), ('ZARANDA', 'Zaranda (Shale Shaker)'), ('SISTEMA_VACIO', 'Sistema de Vacío'), ('CONTENEDOR_RECORTES', 'Contenedor de Recortes'), ('OTROS', 'Otros')], max_length=25, verbose_name='Tipo de Equipo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción de la Propiedad')),
                ('unidad', models.CharField(blank=True, max_length=30, verbose_name='Unidad')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Propiedad de Equipo (Catálogo Maestro)',
                'verbose_name_plural': 'Propiedades de Equipo (Catálogo Maestro)',
                'ordering': ['tipo_equipo', 'orden', 'descripcion'],
                'unique_together': {('tipo_equipo', 'descripcion')},
            },
        ),
        migrations.CreateModel(
            name='BenchmarkTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_max', models.CharField(choices=[('VALOR', 'Valor'), ('MIN', 'Mínimo'), ('MAX', 'Máximo')], default='VALOR', max_length=5, verbose_name='Min/Max')),
                ('valor', models.CharField(blank=True, max_length=50, verbose_name='Valor')),
                ('intervalo', models.ForeignKey(blank=True, help_text="Vacío = 'Whole Well' (todo el pozo).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_targets', to='operaciones.intervalorevestimiento', verbose_name='Intervalo')),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_targets', to='operaciones.pozo')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets_en_pozos', to='operaciones.parametrobenchmark', verbose_name='Parámetro')),
            ],
            options={
                'verbose_name': 'Objetivo de Benchmark',
                'verbose_name_plural': 'Objetivos de Benchmark',
                'ordering': ['parametro__grupo', 'parametro__descripcion', 'min_max'],
                'unique_together': {('pozo', 'parametro', 'intervalo', 'min_max')},
            },
        ),
        migrations.CreateModel(
            name='BenchmarkSeleccionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks_seleccionados', to='operaciones.pozo')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seleccionados_en_pozos', to='operaciones.parametrobenchmark', verbose_name='Parámetro')),
            ],
            options={
                'verbose_name': 'Benchmark Seleccionado',
                'verbose_name_plural': 'Benchmarks Seleccionados',
                'ordering': ['parametro__grupo', 'parametro__descripcion'],
                'unique_together': {('pozo', 'parametro')},
            },
        ),
        migrations.CreateModel(
            name='EquipoPropiedadSeleccionada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('CENTRIFUGA', 'Centrífuga'), ('LIMPIADOR_LODO', 'Limpiador de Lodo (Mud Cleaner)'), ('ZARANDA', 'Zaranda (Shale Shaker)'), ('SISTEMA_VACIO', 'Sistema de Vacío'), ('CONTENEDOR_RECORTES', 'Contenedor de Recortes'), ('OTROS', 'Otros')], max_length=25, verbose_name='Tipo de Equipo')),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades_equipo_seleccionadas', to='operaciones.pozo')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seleccionadas_en_pozos', to='operaciones.propiedadequipotipo', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Propiedad de Equipo Seleccionada',
                'verbose_name_plural': 'Propiedades de Equipo Seleccionadas',
                'ordering': ['tipo_equipo', 'propiedad__orden'],
                'unique_together': {('pozo', 'propiedad')},
            },
        ),
    ]
