# Generated by Django 6.1.1 on 2026-09-20 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_equipo_tipo_equipo_centrifugaunidadconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaExtraLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Plantilla')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Extra Labels',
                'verbose_name_plural': 'Plantillas de Extra Labels',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaExtraLabelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fluido', models.CharField(choices=[('WBM', 'Water-Based Mud'), ('OBM', 'Oil-Based/Synthetic-Based Mud')], max_length=5)),
                ('numero', models.PositiveIntegerField()),
                ('etiqueta', models.CharField(max_length=100)),
                ('unidad', models.CharField(blank=True, max_length=50)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operaciones.plantillaextralabels')),
            ],
            options={
                'verbose_name': 'Item de Plantilla Extra Labels',
                'ordering': ['tipo_fluido', 'numero'],
                'unique_together': {('plantilla', 'tipo_fluido', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='PropiedadExtraFluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fluido', models.CharField(choices=[('WBM', 'Water-Based Mud'), ('OBM', 'Oil-Based/Synthetic-Based Mud')], max_length=5)),
                ('numero', models.PositiveIntegerField(help_text='Numero de propiedad del 1 al 60')),
                ('etiqueta', models.CharField(blank=True, max_length=100, verbose_name='Etiqueta (Label)')),
                ('unidad', models.CharField(blank=True, max_length=50, verbose_name='Unidad (Unit)')),
                ('orden_impresion', models.PositiveIntegerField(default=0, help_text='Orden de impresion en reportes. 0 = oculto.', verbose_name='Print Order')),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades_extra', to='operaciones.pozo')),
            ],
            options={
                'verbose_name': 'Propiedad Extra de Fluido',
                'verbose_name_plural': 'Propiedades Extra de Fluidos',
                'ordering': ['tipo_fluido', 'numero'],
                'unique_together': {('pozo', 'tipo_fluido', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del Reporte')),
                ('tipo_lodo', models.CharField(choices=[('WBM', 'Water Base'), ('WBM_CACL2', 'Water Base (CaCl2)'), ('OBM', 'Oil Base'), ('SBM', 'Synthetic Base')], default='WBM', max_length=20, verbose_name='Tipo de Lodo (Mud Check Type)')),
                ('profundidad_actual', models.FloatField(default=0.0, verbose_name='Profundidad (Depth)')),
                ('profundidad_tvd', models.FloatField(default=0.0, verbose_name='Profundidad TVD')),
                ('bit_depth', models.FloatField(default=0.0, help_text='Disparador principal de la geometría.', verbose_name='Profundidad de Mecha (Bit Depth)')),
                ('actividad_actual', models.CharField(blank=True, max_length=255, verbose_name='Actividad (Present Activity)')),
                ('tipo_fluido_display', models.CharField(blank=True, max_length=150, verbose_name='Nombre Comercial del Fluido (Fluid Type)')),
                ('litologia', models.CharField(blank=True, max_length=150, verbose_name='Litología')),
                ('operador_representante', models.CharField(blank=True, max_length=150, verbose_name='Representante del Operador')),
                ('contratista_representante', models.CharField(blank=True, max_length=150, verbose_name='Representante del Contratista')),
                ('mi_representante_1', models.CharField(blank=True, max_length=150, verbose_name='Ingeniero M-I SWACO 1')),
                ('mi_representante_2', models.CharField(blank=True, max_length=150, verbose_name='Ingeniero M-I SWACO 2')),
                ('telefono_taladro', models.CharField(blank=True, max_length=100, verbose_name='Teléfono del Taladro')),
                ('telefono_almacen', models.CharField(blank=True, max_length=100, verbose_name='Teléfono del Almacén')),
                ('telefonos', models.CharField(blank=True, max_length=255, verbose_name='Otros Teléfonos')),
                ('fax_numbers', models.CharField(blank=True, max_length=255, verbose_name='Pagers/FAX')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_diarios', to='operaciones.pozo')),
            ],
            options={
                'verbose_name': 'Reporte Diario',
                'verbose_name_plural': 'Reportes Diarios',
                'ordering': ['-fecha'],
                'unique_together': {('pozo', 'fecha')},
            },
        ),
    ]
