# Generated by Django 6.1.1 on 2026-09-21 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_plantillaextralabels_plantillaextralabelitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellSurveyStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.PositiveIntegerField(default=1, verbose_name='N° de Estación')),
                ('md_ft', models.FloatField(default=0.0, verbose_name='Profundidad Medida - MD (ft)')),
                ('inclinacion_deg', models.FloatField(default=0.0, verbose_name='Inclinación (°)')),
                ('azimut_deg', models.FloatField(default=0.0, verbose_name='Azimut (°)')),
                ('tvd_ft', models.FloatField(default=0.0, verbose_name='Profundidad Vertical Verdadera - TVD (ft)')),
                ('dls_deg_100ft', models.FloatField(default=0.0, verbose_name='Dogleg Severity (°/100ft)')),
                ('seccion_vertical_ft', models.FloatField(default=0.0, verbose_name='Sección Vertical (ft)')),
                ('comentarios', models.CharField(blank=True, max_length=150, verbose_name='Comentarios')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_stations', to='operaciones.pozo')),
            ],
            options={
                'verbose_name': 'Estación de Well Survey',
                'verbose_name_plural': 'Estaciones de Well Survey',
                'ordering': ['md_ft', 'estacion'],
            },
        ),
    ]
