# Generated by Django 6.1.1 on 2026-09-21 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_wellsurveystation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellFormationTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth_ft', models.FloatField(default=0.0, verbose_name='Depth (ft)')),
                ('formation_top', models.CharField(max_length=150, verbose_name='Formation Top')),
                ('lithology', models.CharField(blank=True, max_length=150, verbose_name='Lithology')),
                ('porcentaje_arena', models.FloatField(default=0.0, verbose_name='% Sand')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_tops', to='operaciones.pozo')),
            ],
            options={
                'verbose_name': 'Tope de Formación y Litología',
                'verbose_name_plural': 'Topes de Formación y Litología',
                'ordering': ['depth_ft', 'id'],
            },
        ),
    ]
