# Generated by Django 6.1.1 on 2026-09-21 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0009_wellformationtop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDiarioBitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bit_description', models.CharField(blank=True, default='Hycalog X-175', max_length=150, verbose_name='Bit Description')),
                ('bit_number', models.CharField(blank=True, default='1', max_length=50, verbose_name='Bit Number')),
                ('washout_pct', models.FloatField(default=0.0, verbose_name='% Washout')),
                ('bit_size', models.FloatField(default=12.25, verbose_name='Bit Size / Hole Diameter (in)')),
                ('washout_hole_size', models.FloatField(default=12.25, verbose_name='Washout Hole Size (in)')),
                ('bit_serial_no', models.CharField(blank=True, max_length=100, verbose_name='Serial Number')),
                ('bit_iadc_code', models.CharField(blank=True, max_length=50, verbose_name='IADC Code')),
                ('bit_manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Manufacturer')),
                ('rotary_rpm', models.FloatField(default=0.0, verbose_name='Rotary RPM')),
                ('rotating_hours', models.FloatField(default=0.0, verbose_name='Rotating Hours')),
                ('weight_on_bit', models.FloatField(default=0.0, verbose_name='Weight on Bit (lbs)')),
                ('rop', models.FloatField(default=0.0, verbose_name='ROP (ft/hr)')),
                ('riser_pump_flow_rate', models.FloatField(default=0.0, verbose_name='Riser Pump Flow Rate (gpm)')),
                ('pump_flow_rate', models.FloatField(default=0.0, verbose_name='Pump Flow Rate (gpm)')),
                ('pump_pressure', models.FloatField(default=0.0, verbose_name='Pump Pressure (psi)')),
                ('dp_mwd', models.FloatField(default=0.0, verbose_name='dP MWD (psi)')),
                ('dp_motor', models.FloatField(default=0.0, verbose_name='dP Motor (psi)')),
                ('motor_rpm', models.FloatField(default=0.0, verbose_name='Motor RPM')),
                ('surface_code', models.CharField(blank=True, default='1', max_length=20, verbose_name='Surface Code (1-5)')),
                ('surface_pressure', models.FloatField(default=0.0, verbose_name='Surface Pressure (psi)')),
                ('ref_flow_rate', models.FloatField(default=0.0, verbose_name='Ref. Flow Rate (gal/min)')),
                ('on_off_bottom_pressure', models.FloatField(default=0.0, verbose_name='On/Off Bottom (psi)')),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bit_data', to='operaciones.reportediario')),
            ],
            options={
                'verbose_name': 'Datos de Barrena y Perforación',
                'verbose_name_plural': 'Datos de Barrena y Perforación',
            },
        ),
        migrations.CreateModel(
            name='ReporteDiarioBoquilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_32nds', models.PositiveIntegerField(default=14, verbose_name='Size (32nds of inch)')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boquillas', to='operaciones.reportediario')),
            ],
            options={
                'verbose_name': 'Boquilla de Barrena',
                'verbose_name_plural': 'Boquillas de Barrena',
                'ordering': ['-size_32nds', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReporteDiarioBomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bomba', models.PositiveIntegerField(default=1, verbose_name='N° Bomba')),
                ('make_model', models.CharField(blank=True, max_length=100, verbose_name='Make and Model')),
                ('liner_diameter', models.FloatField(default=6.5, verbose_name='Liner Diameter (in)')),
                ('stroke_length', models.FloatField(default=12.0, verbose_name='Stroke Length (in)')),
                ('rod_diam_duplex', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Rod Diam Duplex Only (in)')),
                ('eficiencia_pct', models.FloatField(default=97.0, verbose_name='Eff %')),
                ('pump_rate_spm', models.FloatField(default=0.0, verbose_name='Pump Rate (spm)')),
                ('pump_on_report', models.BooleanField(default=True, verbose_name='Pump On Report')),
                ('riser_pump', models.BooleanField(default=False, verbose_name='Riser Pump')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bombas', to='operaciones.reportediario')),
            ],
            options={
                'verbose_name': 'Bomba de Reporte Diario',
                'verbose_name_plural': 'Bombas de Reporte Diario',
                'ordering': ['numero_bomba'],
                'unique_together': {('reporte', 'numero_bomba')},
            },
        ),
    ]
