# Generated by Django 6.1.1 on 2026-09-21 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_reportediariobitdata_reportediarioboquilla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDiarioMudCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.PositiveIntegerField(default=1, verbose_name='N° Chequeo (1-4)')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Check')),
                ('sample_from', models.CharField(blank=True, default='In', max_length=50, verbose_name='Sample From')),
                ('time_taken', models.CharField(blank=True, default='09:00', max_length=20, verbose_name='Time Taken')),
                ('flowline_temp', models.FloatField(blank=True, null=True, verbose_name='Flow Line Temp (°F)')),
                ('depth', models.FloatField(blank=True, null=True, verbose_name='Depth (ft)')),
                ('tvd', models.FloatField(blank=True, null=True, verbose_name='TVD (ft)')),
                ('mud_weight', models.FloatField(blank=True, null=True, verbose_name='Mud Weight (lb/gal)')),
                ('mw_temp', models.FloatField(blank=True, null=True, verbose_name='MW Temp (°F)')),
                ('funnel_viscosity', models.FloatField(blank=True, null=True, verbose_name='Funnel Viscosity (s/qt)')),
                ('rheology_temp', models.FloatField(blank=True, default=120.0, null=True, verbose_name='Rheology Temp (°F)')),
                ('r600', models.FloatField(blank=True, null=True, verbose_name='R600')),
                ('r300', models.FloatField(blank=True, null=True, verbose_name='R300')),
                ('r200', models.FloatField(blank=True, null=True, verbose_name='R200')),
                ('r100', models.FloatField(blank=True, null=True, verbose_name='R100')),
                ('r6', models.FloatField(blank=True, null=True, verbose_name='R6')),
                ('r3', models.FloatField(blank=True, null=True, verbose_name='R3')),
                ('pv', models.FloatField(blank=True, null=True, verbose_name='PV (cP)')),
                ('yp', models.FloatField(blank=True, null=True, verbose_name='YP (lb/100ft²)')),
                ('gel_10s', models.FloatField(blank=True, null=True, verbose_name='10s Gel (lb/100ft²)')),
                ('gel_10m', models.FloatField(blank=True, null=True, verbose_name='10m Gel (lb/100ft²)')),
                ('gel_30m', models.FloatField(blank=True, null=True, verbose_name='30m Gel (lb/100ft²)')),
                ('api_fluid_loss', models.FloatField(blank=True, null=True, verbose_name='API Fluid Loss (cc/30min)')),
                ('hthp_fluid_loss', models.FloatField(blank=True, null=True, verbose_name='HPHT Fluid Loss (cc/30min)')),
                ('cake_api', models.FloatField(blank=True, null=True, verbose_name='Cake API (1/32 in)')),
                ('cake_hthp', models.FloatField(blank=True, null=True, verbose_name='Cake HPHT (1/32 in)')),
                ('solids_pct', models.FloatField(blank=True, null=True, verbose_name='Solids (%Vol)')),
                ('oil_pct', models.FloatField(blank=True, null=True, verbose_name='Oil (%Vol)')),
                ('water_pct', models.FloatField(blank=True, null=True, verbose_name='Water (%Vol)')),
                ('sand_pct', models.FloatField(blank=True, null=True, verbose_name='Sand (%Vol)')),
                ('ph', models.FloatField(blank=True, null=True, verbose_name='pH')),
                ('ph_temp', models.FloatField(blank=True, null=True, verbose_name='pH Temp (°F)')),
                ('pm', models.FloatField(blank=True, null=True, verbose_name='Pm')),
                ('pf', models.FloatField(blank=True, null=True, verbose_name='Pf')),
                ('mf', models.FloatField(blank=True, null=True, verbose_name='Mf')),
                ('chlorides', models.FloatField(blank=True, null=True, verbose_name='Chlorides (mg/L)')),
                ('calcium_hardness', models.FloatField(blank=True, null=True, verbose_name='Hardness Ca++ (mg/L)')),
                ('mbt', models.FloatField(blank=True, null=True, verbose_name='MBT (lb/bbl)')),
                ('electrical_stability', models.FloatField(blank=True, null=True, verbose_name='Electrical Stability (V)')),
                ('excess_lime', models.FloatField(blank=True, null=True, verbose_name='Excess Lime (lb/bbl)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mud_checks', to='operaciones.reportediario')),
            ],
            options={
                'verbose_name': 'Chequeo de Lodo (Mud Check)',
                'verbose_name_plural': 'Chequeos de Lodo (Mud Checks)',
                'ordering': ['check_number'],
                'unique_together': {('reporte', 'check_number')},
            },
        ),
        migrations.CreateModel(
            name='ReporteDiarioMudConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solids_equation', models.CharField(choices=[('M-I', 'M-I SWACO'), ('API', 'API Standard')], default='M-I', max_length=20, verbose_name='Current Solids Analysis Equations')),
                ('is_weighted', models.BooleanField(default=True, verbose_name='Weighted Mud')),
                ('sg_base_oil', models.FloatField(default=0.84, verbose_name='Base Oil S.G.')),
                ('sg_weight_material', models.FloatField(default=4.2, verbose_name='Weight Material S.G.')),
                ('sg_drill_solids', models.FloatField(default=2.6, verbose_name='Drill Solids S.G.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mud_config', to='operaciones.reportediario')),
            ],
            options={
                'verbose_name': 'Configuración de Lodo y Sólidos',
                'verbose_name_plural': 'Configuraciones de Lodo y Sólidos',
            },
        ),
        migrations.CreateModel(
            name='ReporteDiarioMudExtraValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, default='', max_length=100, verbose_name='Valor')),
                ('mud_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_values', to='operaciones.reportediariomudcheck')),
                ('propiedad_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_values', to='operaciones.propiedadextrafluido')),
            ],
            options={
                'verbose_name': 'Valor de Propiedad Extra de Lodo',
                'verbose_name_plural': 'Valores de Propiedades Extra de Lodo',
                'unique_together': {('mud_check', 'propiedad_extra')},
            },
        ),
    ]
