# Generated by Django 6.1.1 on 2026-09-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_reportediariomudcheck_reportediariomudconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='bentonite_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='Bentonite (%Vol)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='bentonite_ppb',
            field=models.FloatField(blank=True, null=True, verbose_name='Bentonite (lb/bbl)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='chem_conc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Chem Conc (lb/bbl)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='drill_solids_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='Drill Solids (%Vol)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='drill_solids_ppb',
            field=models.FloatField(blank=True, null=True, verbose_name='Drill Solids (lb/bbl)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='drill_solids_sg',
            field=models.FloatField(blank=True, default=2.6, null=True, verbose_name='Drill Solids SG'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='frac_bent',
            field=models.FloatField(blank=True, default=0.1111, null=True, verbose_name='Frac Bent (Activity Ratio)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='hgs_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='HGS (%Vol)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='k_from_kcl',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='K+ From KCl (mg/l)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='kcl_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='KCl (%Vol)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='kcl_ppb',
            field=models.FloatField(blank=True, null=True, verbose_name='KCl (lb/bbl)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='lgs_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='LGS (%Vol)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='lgs_ppb',
            field=models.FloatField(blank=True, null=True, verbose_name='LGS (lb/bbl)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='nacl_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='NaCl (%Vol)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='nacl_ppb',
            field=models.FloatField(blank=True, null=True, verbose_name='NaCl (lb/bbl)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='oil_sg',
            field=models.FloatField(blank=True, default=0.7, null=True, verbose_name='Oil SG'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='retort_mud_temp',
            field=models.FloatField(blank=True, default=75.0, null=True, verbose_name='Retort Mud Temp (°F)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='retort_mud_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Retort Mud Wt (lb/gal)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='wt_additive_sg',
            field=models.FloatField(blank=True, default=4.2, null=True, verbose_name='Wt Additive SG'),
        ),
    ]
