# Generated by Django 6.1.1 on 2026-09-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0012_reportediariomudcheck_bentonite_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='adjusted_solids_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='Adjusted Solids (%Vol)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='avg_sg_solids',
            field=models.FloatField(blank=True, null=True, verbose_name='Avg SG Solids'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='hgs_ppb',
            field=models.FloatField(blank=True, null=True, verbose_name='HGS (lb/bbl)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='oil_water_ratio',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Oil/Water Ratio'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='salt_pct_wt',
            field=models.FloatField(blank=True, null=True, verbose_name='Salt (%wt)'),
        ),
        migrations.AddField(
            model_name='reportediariomudcheck',
            name='salt_ppb',
            field=models.FloatField(blank=True, null=True, verbose_name='Salt (lb/bbl)'),
        ),
        migrations.AddField(
            model_name='reportediariomudconfig',
            name='obm_salt_type',
            field=models.CharField(choices=[('CaCl2', 'CaCl2'), ('NaCl', 'NaCl')], default='CaCl2', max_length=10, verbose_name='Internal Phase Salt'),
        ),
    ]
