# Generated by Django 6.1.1 on 2026-09-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0024_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='empaque',
            field=models.CharField(blank=True, default='', help_text='Ej: SACOS, TAMBOR, TOTE, LATA, GRANEL', max_length=50, verbose_name='Empaque'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(help_text='Ej: LBS, GAL, BBL, KG, L', max_length=50, verbose_name='Unidad Física'),
        ),
    ]
