# Generated by Django 6.1 on 2026-08-31 21:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Identificador único del producto (ej. AOS-1001)', max_length=50, unique=True, verbose_name='Código / SKU')),
                ('descripcion', models.CharField(help_text='Nombre descriptivo del producto químico', max_length=255, verbose_name='Descripción')),
                ('unidad', models.CharField(help_text='Ej: TAMBOR 55 GLS, SACOS 55 LBS, TOTEMS 1000 LT', max_length=100, verbose_name='Unidad / Presentación')),
                ('libraje', models.CharField(blank=True, default='N/A', help_text='Libraje o peso neto (ej. 55 LBS, 100 LBS)', max_length=100, verbose_name='Libraje')),
                ('gravedad_especifica', models.CharField(blank=True, default='N/A', help_text='Gravedad específica o densidad técnica', max_length=50, verbose_name='Gravedad Específica')),
                ('cantidad', models.IntegerField(default=0, help_text='Existencia física actual en inventario', verbose_name='Cantidad / Stock Actual')),
                ('stock_inicial', models.IntegerField(default=0, help_text='Existencia al inicio del período o creación', verbose_name='Stock Inicial')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto está disponible en el inventario', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now, unique=True, verbose_name='Fecha del Reporte')),
                ('departamento', models.CharField(default='ALMACÉN', max_length=150, verbose_name='Departamento')),
                ('encargado', models.CharField(default='LUIS BRICEÑO', max_length=150, verbose_name='Encargado')),
                ('elaborado_por_nombre', models.CharField(default='Lusneila Franceschi', max_length=150, verbose_name='Elaborado Por (Nombre)')),
                ('elaborado_por_cargo', models.CharField(default='Administración', max_length=150, verbose_name='Elaborado Por (Cargo)')),
                ('revisado_por_nombre', models.CharField(default='Luis Briceño', max_length=150, verbose_name='Revisado Por (Nombre)')),
                ('revisado_por_cargo', models.CharField(default='Encargado de Almacen', max_length=150, verbose_name='Revisado Por (Cargo)')),
                ('observaciones', models.TextField(blank=True, default='', help_text='Notas o comentarios generales del reporte del día', verbose_name='Observaciones / Comentarios Generales')),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sumatoria automática del costo de los productos usados en el día', max_digits=14, verbose_name='Costo Final Acumulado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Reporte Diario',
                'verbose_name_plural': 'Reportes Diarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, help_text='Número de unidades/bultos retirados del inventario', verbose_name='Cantidad Utilizada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio variable fijado al momento de la salida', max_digits=12, verbose_name='Precio Unitario')),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Costo Subtotal (Cantidad × Precio)')),
                ('observacion', models.TextField(blank=True, default='', help_text='Comentario o justificación del uso de este producto', verbose_name='Observación de la Salida')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Registro')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='mychapala.producto', verbose_name='Producto Utilizado')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='mychapala.reportediario', verbose_name='Reporte Diario Asociado')),
            ],
            options={
                'verbose_name': 'Registro de Uso',
                'verbose_name_plural': 'Registros de Uso',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
