# Generated by Django 6.1.1 on 2026-09-03 21:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychapala', '0002_reportediario_codigo_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('quimico', 'Producto Químico'), ('liquido', 'Producto Líquido'), ('wellsite', 'Wellsite Chemical Inventory')], db_index=True, default='quimico', help_text='Clasificación del producto (Químico, Líquido o Wellsite)', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cum_received',
            field=models.IntegerField(default=0, help_text='Total acumulado recibido', verbose_name="Acumulado Recibido (Cum Rec'd)"),
        ),
        migrations.AddField(
            model_name='producto',
            name='cum_return',
            field=models.IntegerField(default=0, help_text='Total acumulado devuelto', verbose_name='Acumulado Devuelto (Cum Return)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cum_used',
            field=models.IntegerField(default=0, help_text='Cantidad acumulada utilizada (Wellsite)', verbose_name='Acumulado Usado (Cum Used)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='daily_received',
            field=models.IntegerField(default=0, help_text='Cantidad recibida en el día', verbose_name="Recibido Diario (Daily Rec'd)"),
        ),
        migrations.AddField(
            model_name='producto',
            name='daily_return',
            field=models.IntegerField(default=0, help_text='Cantidad devuelta en el día', verbose_name='Devuelto Diario (Daily Return)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo o precio base unitario del producto', max_digits=12, verbose_name='Precio / Costo Unitario ($)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='locacion',
            field=models.CharField(blank=True, default='Offshore', max_length=150, verbose_name='Locación'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='operador',
            field=models.CharField(blank=True, default='Cardon IV', max_length=150, verbose_name='Operador (Wellsite)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='pozo',
            field=models.CharField(blank=True, default='Perla-1X', max_length=150, verbose_name='Pozo / Well Name'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='reporte_no_wellsite',
            field=models.CharField(blank=True, default='16', max_length=50, verbose_name='Report No (Wellsite)'),
        ),
    ]
