# Generated by Django 6.1 on 2026-08-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychapala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportediario',
            name='codigo_reporte',
            field=models.CharField(blank=True, db_index=True, help_text='Ej: REP-2026-0001 o AOS-REP-0001', max_length=50, null=True, unique=True, verbose_name='Número / Identificación del Reporte'),
        ),
    ]
