# Generated by Django 6.1.1 on 2026-09-12 00:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychapala', '0004_producto_unit_size_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportediario',
            name='air_gap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distancia vertical nivel del mar a mesa rotaria', max_digits=10, null=True, verbose_name='Air Gap (ft)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='bit_depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profundidad actual de la mecha', max_digits=10, null=True, verbose_name='Bit Depth (ft)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='bit_size',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Diámetro de la mecha', max_digits=6, null=True, verbose_name='Bit Size (in)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='porcentaje_washout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de ensanchamiento del hoyo', max_digits=5, verbose_name='% Washout'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='riser_id',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Riser ID (in)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='riser_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longitud efectiva (Water Depth - Air Gap)', max_digits=10, null=True, verbose_name='Riser Length (ft)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='riser_od',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Riser OD (in)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='riserless_drilling',
            field=models.BooleanField(default=True, help_text='Activo si no se utiliza riser en perforación marina', verbose_name='¿Riserless Drilling?'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='tipo_seccion_hoyo',
            field=models.CharField(blank=True, choices=[('casing', 'Casing'), ('liner', 'Liner'), ('open_hole', 'Open Hole')], default='open_hole', max_length=20, verbose_name='Tipo de Sección del Hoyo'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='total_perdidas_mecanicas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Pérdidas Mecánicas (bbl)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='total_perdidas_subsuelo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Pérdidas de Subsuelo (bbl)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='total_perdidas_superficie',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Pérdidas de Superficie (bbl)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='volumen_anular',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Volumen Anular (Annulus, bbl)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='volumen_debajo_mecha',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Volumen Debajo de Mecha (Below Bit, bbl)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='volumen_medido_fosas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Volumen Medido Fosas (Actual End Volume, bbl)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='volumen_no_fluido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Volumen No Fluido (Volume Not Fluids, bbl)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='volumen_sarta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Volumen Sarta (Total DS, bbl)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='volumen_teorico_fosas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Volumen Teórico Fosas (Calc End Volume, bbl)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='water_depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profundidad de agua (Offshore)', max_digits=10, null=True, verbose_name='Water Depth (ft)'),
        ),
        migrations.CreateModel(
            name='Fosa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre / Descripción de la Fosa')),
                ('tipo', models.CharField(choices=[('active', 'Active'), ('reserve', 'Reserve'), ('premix', 'Premix'), ('spacer', 'Spacer'), ('storage', 'Storage (Non-Transactional)'), ('dead_volume', 'Dead Volume')], default='active', max_length=20)),
                ('capacidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Capacidad Máxima (bbl)')),
                ('volumen_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Start Volume (bbl)')),
                ('volumen_final_teorico', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Calc End Volume (bbl)')),
                ('volumen_final_medido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Actual End Volume (bbl)')),
                ('peso_lodo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Fluid Weight (ppg)')),
                ('es_transaccional', models.BooleanField(default=True, help_text='Si es False, es almacenamiento pasivo (Non-Transactional Pits) que no entra en el balance activo', verbose_name='¿Es transaccional?')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fosas', to='mychapala.reportediario', verbose_name='Reporte Diario')),
            ],
            options={
                'verbose_name': 'Fosa / Tanque',
                'verbose_name_plural': 'Fosas y Tanques (Pit Section)',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Desplazamiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_componente', models.CharField(choices=[('spacer', 'Espaciador'), ('viscous_pill', 'Píldora Viscosa'), ('brine', 'Salmuera'), ('mud', 'Lodo'), ('water', 'Agua de Lavado')], default='spacer', max_length=30, verbose_name='Tipo de Componente (Tren de Baches)')),
                ('descripcion', models.CharField(blank=True, default='', max_length=150, verbose_name='Descripción / Nombre del Bache')),
                ('volumen', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Volumen del Componente (bbl)')),
                ('reclaimed', models.BooleanField(default=False, help_text='Controla si el fluido retornado a superficie se recupera en tanques', verbose_name='¿Recuperado en Superficie (Reclaimed)?')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden en el Tren de Baches')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones de la Maniobra')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desplazamientos', to='mychapala.reportediario', verbose_name='Reporte Diario')),
                ('fosa_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='desplazamientos_origen', to='mychapala.fosa', verbose_name='Fosa de Mezcla Previa (Precondición de Volume Accounting)')),
                ('fosa_retorno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desplazamientos_retorno', to='mychapala.fosa', verbose_name='Tanque de Retorno (Reclaimed to Pit)')),
            ],
            options={
                'verbose_name': 'Desplazamiento / Bache',
                'verbose_name_plural': 'Desplazamientos (Displacements Tab)',
                'ordering': ['reporte', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='GeometriaHoyo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('casing', 'Casing'), ('liner', 'Liner'), ('open_hole', 'Open Hole')], default='open_hole', max_length=20, verbose_name='Tipo de Sección')),
                ('diametro', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Diámetro / Hole Size (in)')),
                ('profundidad_tope', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Profundidad Tope (ft)')),
                ('profundidad_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Profundidad Base (ft)')),
                ('capacidad', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10, verbose_name='Capacidad (bbl/ft)')),
                ('volumen', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Volumen Sección (bbl)')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometrias_hoyo', to='mychapala.reportediario', verbose_name='Reporte Diario')),
            ],
            options={
                'verbose_name': 'Geometría del Hoyo',
                'verbose_name_plural': 'Geometrías del Hoyo (Wellbore Geometry)',
                'ordering': ['profundidad_tope'],
            },
        ),
        migrations.CreateModel(
            name='TramoSarta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('drill_pipe', 'Drill Pipe'), ('heavy_weight', 'Heavy Weight Drill Pipe'), ('drill_collar', 'Drill Collar'), ('sub', 'Sub / Herramienta BHA')], default='drill_pipe', max_length=30)),
                ('diametro_externo', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='OD (in)')),
                ('diametro_interno', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='ID (in)')),
                ('longitud', models.DecimalField(blank=True, decimal_places=2, help_text='Si es el componente superior (Drill Pipe), se autocalcula como Bit Depth - sum(BHA)', max_digits=10, null=True, verbose_name='Longitud (ft)')),
                ('es_principal', models.BooleanField(default=False, help_text='El primer tramo cuya longitud absorbe la profundidad de la mecha', verbose_name='¿Es tramo principal?')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_sarta', to='mychapala.reportediario', verbose_name='Reporte Diario Asociado')),
            ],
            options={
                'verbose_name': 'Tramo de Sarta',
                'verbose_name_plural': 'Tramos de Sarta (Drill String)',
            },
        ),
        migrations.CreateModel(
            name='TransaccionVolumetrica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('add_chemicals', 'Add Chemicals'), ('add_whole_mud', 'Add Whole Mud'), ('transfer', 'Transfer'), ('return_back_load', 'Return (Back Load)'), ('equipment_loss', 'Create Equipment Loss Transaction')], max_length=30)),
                ('volumen', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Volumen (bbl)')),
                ('is_dilution', models.BooleanField(default=False, help_text='Etiqueta el movimiento como táctica de reducción de sólidos de baja gravedad (LGS)', verbose_name='¿Es Dilución (Is Dilution)?')),
                ('add_without_charge', models.BooleanField(default=False, help_text='Saltea la facturación si el lodo a granel pertenece a la operadora', verbose_name='¿Agregar Sin Cargo (Add Without Charge)?')),
                ('all_volume', models.BooleanField(default=False, help_text='Vacía a cero la fosa origen previniendo residuos decimales', verbose_name='¿Todo el Volumen (All Volume)?')),
                ('comentario', models.TextField(blank=True, default='', verbose_name='Comentario de la Transacción')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('fosa_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_entrada', to='mychapala.fosa', verbose_name='Fosa Destino')),
                ('fosa_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_salida', to='mychapala.fosa', verbose_name='Fosa Origen')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_volumen', to='mychapala.producto', verbose_name='Producto Asociado')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_volumetricas', to='mychapala.reportediario', verbose_name='Reporte Diario')),
            ],
            options={
                'verbose_name': 'Transacción Volumétrica',
                'verbose_name_plural': 'Transacciones Volumétricas (Transaction Buttons)',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
