# Generated by Django 6.1.1 on 2026-09-12 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychapala', '0005_reportediario_air_gap_reportediario_bit_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desplazamiento',
            name='fosa_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desplazamientos_origen', to='mychapala.fosa', verbose_name='Fosa de Mezcla Previa (Precondición de Volume Accounting)'),
        ),
    ]
