# Generated by Django 6.1.1 on 2026-09-12 01:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychapala', '0006_alter_desplazamiento_fosa_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportediario',
            name='circulating_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Horas de circulación en 24h', max_digits=5, null=True, verbose_name='Horas Circulando'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='midnight_depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profundidad a las 00:00 hrs', max_digits=10, null=True, verbose_name='Midnight Depth (ft)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='rotating_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Horas de rotación en 24h', max_digits=5, null=True, verbose_name='Horas Rotando'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='total_depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profundidad total medida del pozo', max_digits=10, null=True, verbose_name='Total Depth (MD) (ft)'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='tvd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profundidad vertical verdadera', max_digits=10, null=True, verbose_name='True Vertical Depth (ft)'),
        ),
        migrations.AlterField(
            model_name='tramosarta',
            name='diametro_externo',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, verbose_name='OD (in)'),
        ),
        migrations.AlterField(
            model_name='tramosarta',
            name='diametro_interno',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, verbose_name='ID (in)'),
        ),
    ]
